Reset refactor, handling save errors in case of successfull save
bbxdeveloper/bbxUI pull request #35
Opened 2023-03-08 16:50 UTC by C-63

2023-03-08 17:12 UTC, pkCrazy requested changes

2023-03-08 17:12 UTC, pkCrazy commented on src/app/modules/offer/offer-creator/offer-creator.component.ts
> +                if (!!d.data) {
Ez az`if` felesleges.

2023-03-08 20:18 UTC, szdezso approved these changes

2023-03-09 18:44 UTC, pkCrazy approved these changes

2023-03-09 18:44 UTC, merged